services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sep_drive_docker
      POSTGRES_USER: sep_drive
      POSTGRES_PASSWORD: sep_drive
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sep_drive_docker
      DB_USER: sep_drive
      DB_PASS: sep_drive
      UPLOAD_DIR: /uploads
    env_file:
      - .env
    volumes:
      - upload_data:/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src/app
    depends_on:
      - backend


volumes:
  pg_data:
  upload_data: