/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the data of an account.
 */
export interface AccountDTO { 
    /**
     * The unique username of the account.
     */
    username: string;
    /**
     * The email address of the account.
     */
    email: string;
    /**
     * The role of the user ( \'CUSTOMER\' or \'DRIVER\' ).
     */
    role: string;
    /**
     * First name of the account holder.
     */
    firstName: string;
    /**
     * Last name of the account holder.
     */
    lastName: string;
    /**
     * URL to the profile picture (optional).
     */
    profilePictureUrl?: string;
    /**
     * The type of car associated with the account (when the person is a driver its cannot be null). Should be null if the user is a customer.
     */
    carType?: AccountDTO.CarTypeEnum;
    /**
     * Date of birth in the format YYYY-MM-DD.
     */
    birthday: string;
    /**
     * List of ratings associated with this account .
     */
    ratings: number;
    /**
     * The total number of rides the account holder has taken.
     */
    totalNumberOfRides: number;
    /**
     * the total bank balance in the account
     */
    balance: number;
}
export namespace AccountDTO {
    export const CarTypeEnum = {
        Small: 'SMALL',
        Medium: 'MEDIUM',
        Deluxe: 'DELUXE'
    } as const;
    export type CarTypeEnum = typeof CarTypeEnum[keyof typeof CarTypeEnum];
}


