/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Driver } from './driver';


/**
 * Represents the information of an account.
 */
export interface Account { 
    /**
     * The username of the account.
     */
    username: string;
    /**
     * The role of the account.
     */
    role: string;
    /**
     * The first name of the user.
     */
    firstName: string;
    /**
     * The last name of the user.
     */
    lastName: string;
    /**
     * The email of the user.
     */
    email: string;
    /**
     * The birth date of the user.
     */
    birthDate: string;
    /**
     * The url to the profile picture. Might be null if user has no profile picture.
     */
    profilePictureUrl?: string;
    /**
     * The rating of the user.
     */
    rating: number;
    /**
     * The count of trips the user has made.
     */
    tripCount: number;
    driver?: Driver;
}

