/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *  Tabelle-Informationen der verfügbaren Fahranfragen 
 */
export interface AvailableTripRequestDTO { 
    /**
     * requestId der Fahrt 
     */
    requestId: number;
    /**
     *  Erstellungsdatum und-uhrzeit der Fahranfrage 
     */
    requestTime: string;
    /**
     *  Kundenname
     */
    customerUsername: string;
    /**
     * Kundenbewertung
     */
    customerRating: number;
    /**
     *  Gewünschte Fahrzeugklasse
     */
    desiredCarType: string;
    /**
     * Entfernung zwischen der aktuellen Position des Fahrers und dem Startpunkt der Fahrt
     */
    distanceInKm: number;
    /**
     * Gesamte Distance der Fahrt 
     */
    totalDistanceInKm: number;
    /**
     * Gesamte Preis der Fahrt 
     */
    price: number;
    /**
     * Gesamte Dauer der Fahrt in Sekunde 
     */
    duration: number;
}

