/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a coordinate.
 */
export interface Coordinate { 
    /**
     * The latitude.
     */
    latitude: number;
    /**
     * The longitude.
     */
    longitude: number;
}

