/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TripHistoryEntity } from './tripHistoryEntity';
import { TripRequestEntity } from './tripRequestEntity';


export interface CustomerEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    email?: string;
    username?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
    verified: boolean;
    birthday: string;
    profilePictureUrl?: string;
    balance?: number;
    tripHistories?: Array<TripHistoryEntity>;
    tripRequest?: Array<TripRequestEntity>;
}

