/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TripHistoryEntity } from './tripHistoryEntity';


export interface DriverEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    email?: string;
    username?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
    verified: boolean;
    birthday: string;
    profilePictureUrl?: string;
    balance?: number;
    carType?: string;
    tripHistories?: TripHistoryEntity[];
}

