/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents additional statistics of a driver.
 */
export interface DriverStatistics { 
    /**
     * The username of the driver.
     */
    driverUsername: string;
    /**
     * The first name of the driver.
     */
    driverFirstName: string;
    /**
     * The last name of the driver.
     */
    driverLastName: string;
    /**
     * The average rating of the driver.
     */
    averageRating: number;
    /**
     * The number of trips the driver has made.
     */
    totalTrips: number;
    /**
     * The total distance driven by the driver.
     */
    totalDistance: number;
}

