/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents an error response with status code and message.
 */
export interface ErrorResponse { 
    /**
     * The status code of the error response.
     */
    statusCode?: number;
    /**
     * The message of the error response.
     */
    message?: string;
}

