/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * FahrerLeaderboard
 */
export interface Leaderboard { 
    /**
     * username des Fahrers
     */
    driverUsername: string;
    /**
     * Name des Fahrers(Vor- und Nachname
     */
    driverName: string;
    /**
     * Gesamte gefahrene Distance
     */
    totalDrivenDistance: number;
    /**
     * Gesamte Fahrzeit
     */
    averageRating: number;
    /**
     * Gesamte Fahrzeit
     */
    totalDriveTime: number;
    /**
     * Gesamte Anzahl der gefahrenen Trips
     */
    totalNumberOfDrivenTrip: number;
    /**
     * Total verdientes Geld
     */
    totalEarnings: number;
}

