/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TripRequestEntity } from './tripRequestEntity';
import { RouteEntity } from './routeEntity';
import { NominatimFeature } from './nominatimFeature';


export interface LocationEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    displayName?: string;
    longitude?: number;
    latitude?: number;
    route?: RouteEntity;
    tripRequest?: TripRequestEntity;
    geoJSON?: NominatimFeature;
}

