/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NominatimFeature } from './nominatimFeature';


export interface Location { 
    /**
     * The id of the location. Might be null if location does not have related entity.
     */
    locationId?: number;
    /**
     * The longitude of the location.
     */
    longitude: number;
    /**
     * The latitude of the location.
     */
    latitude: number;
    /**
     * The display name of the location.
     */
    displayName: string;
    geoJSON?: NominatimFeature;
}

