/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a DTO for a location.
 */
export interface LocationDTO { 
    /**
     * The latitude of the location.
     */
    latitude: number;
    /**
     * The longitude of the location.
     */
    longitude: number;
    /**
     * The displayName of the location.
     */
    displayName: string;
}

