/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for Location
 */
export interface LocationDTO { 
    /**
     * Display name of location
     */
    display_name: string;
    /**
     * Latitude of location
     */
    lat: number;
    /**
     * Longitude of location
     */
    lon: number;
}

