/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { NominatimFeature } from './nominatimFeature';


export interface Location { 
    /**
     * The id of the location. Might be null if location does not have related entity.
     */
    locationId?: number;
    coordinate: Coordinate;
    /**
     * The display name of the location.
     */
    displayName: string;
    geoJSON: NominatimFeature;
}

