/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a login auth request.
 */
export interface LoginRequest { 
    /**
     * The unique identifier of the user. Either the email or the username.
     */
    uniqueIdentifier: string;
    /**
     * The password of the user.
     */
    password: string;
}

