/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
<<<<<<<< HEAD:frontend/src/api/sep_drive/model/oRSSummary.ts
 * Represents the summary of a request made by ORS.
 */
export interface ORSSummary { 
    /**
     * The total distance.
     */
    distance: number;
    /**
     * The total duration.
     */
    duration: number;
========
 * Represents a GeoJSON Geometry as standardized by RFC 7946.
 */
export interface NominatimGeometry { 
    /**
     * The geometry type.
     */
    type: string;
    /**
     * The coordinates of the geometry.
     */
    coordinates: Array<number>;
>>>>>>>> origin/profile:frontend/src/api/sep_drive/model/nominatimGeometry.ts
}

