/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NominatimProperties } from './nominatimProperties';
import { NominatimGeometry } from './nominatimGeometry';


/**
 * Represents a GeoJSON Feature as standardized by RFC 7946.
 */
export interface NominatimFeature { 
    /**
     * The feature type.
     */
    type: string;
    /**
     * The bounding box.
     */
    bbox: Array<number>;
    properties: NominatimProperties;
    geometry: NominatimGeometry;
}

