/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a GeoJSON Geometry as standardized by RFC 7946.
 */
export interface NominatimGeometry { 
    /**
     * The geometry type.
     */
    type: string;
    /**
     * The coordinates of the geometry.
     */
    coordinates: Array<number>;
}

