/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the properties of a nominatim feature.
 */
export interface NominatimProperties { 
    /**
     * The place id of the feature.
     */
    place_id: string;
    /**
     * The osm type of the feature.
     */
    osm_type: string;
    /**
     * The osm id of the feature.
     */
    osm_id: string;
    /**
     * The place rank of the feature.
     */
    place_rank: string;
    /**
     * The category of the feature.
     */
    category: string;
    /**
     * The type of the feature.
     */
    type: string;
    /**
     * The importance of the feature.
     */
    importance: number;
    /**
     * The address type of the feature.
     */
    addresstype: string;
    /**
     * The name of the feature.
     */
    name: string;
    /**
     * The display name of the feature.
     */
    display_name: string;
}

