/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a notification.
 */
export interface Notification { 
    /**
     * The unique id of the notification.
     */
    id: number;
    /**
     * The type of the notification.
     */
    notificationType: Notification.NotificationTypeEnum;
    /**
     * The message of the notification.
     */
    message: string;
}
export namespace Notification {
    export const NotificationTypeEnum = {
        TripOfferNew: 'TRIP_OFFER_NEW',
        TripOfferRevoked: 'TRIP_OFFER_REVOKED',
        TripOfferAccepted: 'TRIP_OFFER_ACCEPTED',
        TripOfferRejected: 'TRIP_OFFER_REJECTED'
    } as const;
    export type NotificationTypeEnum = typeof NotificationTypeEnum[keyof typeof NotificationTypeEnum];
}


