/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a notification.
 */
export interface Notification { 
    /**
     * The unique id of the notification.
     */
    id: number;
    /**
     * The type of the notification.
     */
    notificationType: string;
    /**
     * The message of the notification.
     */
    message: string;
}

