/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the ORS engine information.
 */
export interface ORSEngine { 
    /**
     * The version of the engine.
     */
    version: string;
    /**
     * The build date of the engine.
     */
    build_date: string;
    /**
     * The graph date of the engine.
     */
    graph_date: string;
}

