/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSFeature } from './oRSFeature';
import { ORSMetadata } from './oRSMetadata';


/**
 * Represents the GeoJSON FeatureCollection.
 */
export interface ORSFeatureCollection { 
    /**
     * The feature collection type.
     */
    type: ORSFeatureCollection.TypeEnum;
    /**
     * The bounding box.
     */
    bbox: [number, number, number, number];
    /**
     * The features.
     */
    features: ORSFeature[];
    metadata: ORSMetadata;
}
export namespace ORSFeatureCollection {
    export const TypeEnum = {
        Point: 'Point',
        MultiPoint: 'MultiPoint',
        LineString: 'LineString',
        MultiLineString: 'MultiLineString',
        Polygon: 'Polygon',
        MultiPolygon: 'MultiPolygon',
        GeometryCollection: 'GeometryCollection',
        Feature: 'Feature',
        FeatureCollection: 'FeatureCollection'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


