/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSFeature } from './oRSFeature';
import { ORSMetadata } from './oRSMetadata';


/**
 * Represents the GeoJSON FeatureCollection.
 */
export interface ORSFeatureCollection {
    /**
     * The feature collection type.
     */
    type: string;
    /**
     * The bounding box.
     */
    bbox?: Array<number>;
    /**
     * The features.
     */
    features: Array<ORSFeature>;
    metadata?: ORSMetadata;
}

