/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSProperties } from './oRSProperties';
import { ORSGeometry } from './oRSGeometry';


/**
 * Represents a GeoJSON Feature as standardized by RFC 7946.
 */
export interface ORSFeature { 
    /**
     * The feature type.
     */
    type: string;
    /**
     * The bounding box.
     */
    bbox: number[];
    properties: ORSProperties;
    geometry: ORSGeometry;
}

