/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSEngine } from './oRSEngine';
import { ORSQuery } from './oRSQuery';


/**
 * Represents the meta data produces by ORS.
 */
export interface ORSMetadata { 
    /**
     * The attribution.
     */
    attribution: string;
    /**
     * The service.
     */
    service: string;
    /**
     * The timestamp.
     */
    timestamp: number;
    query: ORSQuery;
    engine: ORSEngine;
}

