/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSSummary } from './oRSSummary';
import { ORSSegment } from './oRSSegment';


/**
 * Represents the properties of a feature.
 */
export interface ORSProperties { 
    /**
     * The segments.
     */
    segments: Array<ORSSegment>;
    /**
     * The way points.
     */
    way_points: Array<number>;
    summary: ORSSummary;
}

