/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSSummary } from './oRSSummary';
import { ORSSegment } from './oRSSegment';


/**
 * Represents the properties of a feature.
 */
export interface ORSProperties { 
    /**
     * The segments.
     */
    segments: ORSSegment[];
    /**
     * The way points.
     */
    way_points: number[];
    summary: ORSSummary;
}

