/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a query.
 */
export interface ORSQuery { 
    /**
     * The coordinates.
     */
    coordinates: number[][];
    /**
     * The profile.
     */
    profile: string;
    /**
     * The name of the profile.
     */
    profileName: string;
    /**
     * The format.
     */
    format: string;
}

