/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSStep } from './oRSStep';


/**
 * Represents a segment.
 */
export interface ORSSegment { 
    /**
     * The distance for the segment.
     */
    distance: number;
    /**
     * The duration for the segment.
     */
    duration: number;
    /**
     * The steps of the segment.
     */
    steps: Array<ORSStep>;
}

