/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the summary of a request made by ORS.
 */
export interface ORSSummary { 
    /**
     * The total distance.
     */
    distance: number;
    /**
     * The total duration.
     */
    duration: number;
}

