/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a step.
 */
export interface ORSStep { 
    /**
     * The distance.
     */
    distance: number;
    /**
     * The duration.
     */
    duration: number;
    /**
     * The type.
     */
    type: number;
    /**
     * The instruction.
     */
    instruction: string;
    /**
     * The name.
     */
    name: string;
    /**
     * The way points.
     */
    way_points: Array<number>;
}

