/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The final request with the OTP.
 */
export interface OtpRequest { 
    /**
     * The unique identifier of the user.
     */
    uniqueIdentifier: string;
    /**
     * The OTP of the user.
     */
    otp: string;
}

