/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the common registration data of a user.
 */
export interface RegistrationDTO { 
    /**
     * The email of the user.
     */
    email: string;
    /**
     * The username of the user.
     */
    username: string;
    /**
     * The password of the user.
     */
    password: string;
    /**
     * The firstname of the user.
     */
    firstName: string;
    /**
     * The lastname of the user.
     */
    lastName: string;
    /**
     * The birthday of the user.
     */
    birthday: string;
    /**
     * The role of the user. Either CUSTOMER or DRIVER.
     */
    role: string;
    /**
     * The type of the car by the driver. Either SMALL, MEDIUM or DELUXE. Might be null if user is a customer.
     */
    carType?: RegistrationDTO.CarTypeEnum;
}
export namespace RegistrationDTO {
    export const CarTypeEnum = {
        Small: 'SMALL',
        Medium: 'MEDIUM',
        Deluxe: 'DELUXE'
    } as const;
    export type CarTypeEnum = typeof CarTypeEnum[keyof typeof CarTypeEnum];
}


