/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSFeatureCollection } from './oRSFeatureCollection';
import { Location } from './location';


/**
 * Represents the information of a route.
 */
export interface Route { 
    /**
     * The id of the route.
     */
    routeId: number;
    /**
     * The stops of the route.
     */
    stops: Location[];
    geoJson: ORSFeatureCollection;
}

