/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSFeatureCollection } from './oRSFeatureCollection';
import { Location } from './location';


/**
 * Represents a Route request.
 */
export interface RouteDTO { 
    id: RouteDTO;
    /**
     * A list of stops.
     */
    stops?: Location[];
    geojson?: ORSFeatureCollection;
}

