/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationEntity } from './locationEntity';
import { ORSFeatureCollection } from './oRSFeatureCollection';
import { TripRequestEntity } from './tripRequestEntity';


export interface RouteEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    stops?: LocationEntity[];
    tripRequest?: TripRequestEntity;
    geoJSON?: ORSFeatureCollection;
}

