/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { Location } from './location';


export interface RouteUpdateRequestBody { 
    currentCoordinate: Coordinate;
    /**
     * The locations of the route.
     */
    locations: Location[];
}

