/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationActionParameters } from './simulationActionParameters';


/**
 * Represents an inbound simulation action.
 */
export interface SimulationAction { 
    /**
     * The type of the action.
     */
    actionType: SimulationAction.ActionTypeEnum;
    /**
     * The timestamp of the action.
     */
    timestamp: string;
    parameters: SimulationActionParameters;
}
export namespace SimulationAction {
    export type ActionTypeEnum = 'START' | 'STOP' | 'CHANGE_VELOCITY' | 'COMPLETE' | 'INFO' | 'LOCK' | 'UNLOCK';
    export const ActionTypeEnum = {
        Start: 'START' as ActionTypeEnum,
        Stop: 'STOP' as ActionTypeEnum,
        ChangeVelocity: 'CHANGE_VELOCITY' as ActionTypeEnum,
        Complete: 'COMPLETE' as ActionTypeEnum,
        Info: 'INFO' as ActionTypeEnum,
        Lock: 'LOCK' as ActionTypeEnum,
        Unlock: 'UNLOCK' as ActionTypeEnum
    };
}


