/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimulationActionParameters } from './simulationActionParameters';


/**
 * Represents an inbound simulation action.
 */
export interface SimulationAction { 
    /**
     * The type of the action.
     */
    actionType: SimulationAction.ActionTypeEnum;
    /**
     * The timestamp of the action.
     */
    timestamp: string;
    parameters: SimulationActionParameters;
}
export namespace SimulationAction {
    export const ActionTypeEnum = {
        Start: 'START',
        Stop: 'STOP',
        RerouteLock: 'REROUTE_LOCK',
        RerouteUnlock: 'REROUTE_UNLOCK',
        RerouteDriver: 'REROUTE_DRIVER',
        AckRerouteDriver: 'ACK_REROUTE_DRIVER',
        ChangeVelocity: 'CHANGE_VELOCITY',
        Complete: 'COMPLETE',
        Info: 'INFO',
        Lock: 'LOCK',
        Unlock: 'UNLOCK',
        DriverPresent: 'DRIVER_PRESENT',
        AckDriverPresent: 'ACK_DRIVER_PRESENT',
        CustomerPresent: 'CUSTOMER_PRESENT',
        AckCustomerPresent: 'ACK_CUSTOMER_PRESENT'
    } as const;
    export type ActionTypeEnum = typeof ActionTypeEnum[keyof typeof ActionTypeEnum];
}


