/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents all possible parameters of different simulation actions.
 */
export interface SimulationActionParameters { 
    /**
     * The start index of the simulation.
     */
    startIndex: number;
    /**
     * The velocity of the simulation.
     */
    velocity?: number;
    /**
     * The rating of the user.
     */
    rating?: number;
}

