/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StatisticsResponse { 
    /**
     * The type of Data
     */
    type: string;
    /**
     * The time interval
     */
    interval: string;
    /**
     * The data
     */
    data: number[];
}

