/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A wrapper for a response containing only a string.
 */
export interface StringResponse { 
    /**
     * The string of the response.
     */
    message: string;
}

