/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Transaction { 
    /**
     * The type of the transaction.
     */
    transactionType: string;
    /**
     * The amount of the transaction.
     */
    amount: number;
    /**
     * The sender of the transaction. Might be null if action was DEPOSIT or WITHDRAW.
     */
    senderUsername?: string;
    /**
     * The recipient of the transaction. Might be null if action was DEPOSIT or WITHDRAW.
     */
    recipientUsername?: string;
}

