/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *  Trip-history eines Fahrers oder Kunden 
 */
export interface TripHistoryDTO { 
    /**
     * die Id von der fahrt
     */
    tripId: number;
    /**
     *  Das Abschlussdatum und die Uhrzeit
     */
    endTime: string;
    /**
     *  Die gefahrene Distanz
     */
    distance: number;
    /**
     *   Die Fahrtdauer
     */
    duration: number;
    /**
     * Das gezahlte oder erhaltene Geld
     */
    price: number;
    /**
     *  Die Bewertung des Kundens 
     */
    driverRating: number;
    /**
     *  Die Bewertung des Fahrers
     */
    customerRating: number;
    /**
     *  Name des Kundens (Vor und Nachname ) 
     */
    customerName: string;
    /**
     * Benutzername des Kundens
     */
    customerUsername: string;
    /**
     * Name des Fahrers (Vor und Nachname)
     */
    driverName: string;
    /**
     * Benutzername des Fahrers 
     */
    driverUsername: string;
}

