/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { Route } from './route';


/**
 * The trip request belonging to the trip offer.
 */
export interface TripRequest { 
    /**
     * The id of the trip request.
     */
    id: number;
    customer: Account;
    route: Route;
    /**
     * The requested car type for the trip request.
     */
    carType: string;
    /**
     * The status of the trip request. Either ACTIVE or DELETED.
     */
    status: string;
    /**
     * The price for the trip request in euro.
     */
    price: number;
}

