/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RouteDTO } from './routeDTO';


/**
 * Represents a request for a drive.
 */
export interface TripRequestDTO { 
    /**
     * Unique id of trip request.
     */
    tripRequestId: number;
    /**
     * The customer requesting drive.
     */
    email: string;
    route: RouteDTO;
    /**
     * The type of car requested.
     */
    carType: string;
    /**
     * The optional notes for the driver.
     */
    note?: string;
    /**
     * The current status of the trip. Either ACTIVE or DELETED.
     */
    status: string;
    /**
     * The price for the trip request.
     */
    price: number;
}

