/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';


/**
 * Represents a request for a drive.
 */
export interface TripRequestDTO { 
    /**
     * The customer requesting drive.
     */
    email: string;
    startLocation: Location;
    endLocation: Location;
    /**
     * The type of car requested.
     */
    carType: string;
    /**
     * The optional notes for the driver.
     */
    note?: string;
    /**
     * The current status of the trip. Either ACTIVE or DELETED.
     */
    status?: string;
}

