/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a trip offer.
 */
export interface TripOfferResponse { 
    /**
     * Username
     */
    username: string;
    /**
     * First name
     */
    firstName: string;
    /**
     * Last name
     */
    lastName: string;
    /**
     * Rating
     */
    rating?: number;
    /**
     * Total drive count
     */
    totalDriveCount: number;
    /**
     * Total drive distance
     */
    driveDistance: number;
}

