/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerEntity } from './customerEntity';
import { TripOfferEntity } from './tripOfferEntity';
import { RouteEntity } from './routeEntity';


export interface TripRequestEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    customer?: CustomerEntity;
    route?: RouteEntity;
    requestTime?: string;
    offers?: Array<TripOfferEntity>;
    carType?: string;
    status?: string;
    price?: number;
}

