/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ORSFeatureCollection } from './oRSFeatureCollection';
import { Location } from './location';


/**
 * Represents a request for a drive.
 */
export interface TripRequestDTO { 
    /**
     * Eindeutige ID der Fahranfrage
     */
    tripRequestId: number;
    /**
     * Zeitpunkt der Anfrage
     */
    createdAt: string;
    /**
     * The customer requesting drive.
     */
    email: string;
    startLocation: Location;
    endLocation: Location;
    /**
     * The type of car requested.
     */
    desiredCarType: string;
    /**
     * Die Optionale Zwischenstops während der Fahrt 
     */
    stops?: Array<Location>;
    /**
     * The optional notes for the driver.
     */
    note?: string;
    /**
     * The current status of the trip. Either ACTIVE or DELETED.
     */
    status: string;
    geoJson: ORSFeatureCollection;
}

