/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location } from './location';


/**
 * Represents the body of a creation request for a trip.
 */
export interface TripRequestBody { 
    startLocation: Location;
    endLocation: Location;
    /**
     * The type of car requested.
     */
    desiredCarType: string;
    /**
     * The optional notes by the customer.
     */
    note?: string;
}

