/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerEntity } from './customerEntity';
import { DriverEntity } from './driverEntity';


export interface TripHistoryEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    tripOfferId?: number;
    endTime?: string;
    distance?: number;
    duration?: number;
    price?: number;
    driverRating?: number;
    customerRating?: number;
    driver?: DriverEntity;
    customer?: CustomerEntity;
}

