/**
 * SEP-Drive Gruppe P API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { TripRequest } from './tripRequest';
import { DriverStatistics } from './driverStatistics';


export interface TripOffer { 
    /**
     * The id of the trip offer.
     */
    id: number;
    tripRequest: TripRequest;
    driver: Account;
    driverStatistics: DriverStatistics;
    /**
     * The status of the trip offer. Either PENDING, ACCEPTED, DECLINED, WITHDRAWN or COMPLETED.
     */
    status: string;
}

