/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { TripRequest } from './tripRequest';
import { DriverStatistics } from './driverStatistics';


export interface TripOffer { 
    /**
     * The if of the trip offer.
     */
    id: number;
    tripRequest: TripRequest;
    driver: Account;
    driverStatistics: DriverStatistics;
    /**
     * The status of the trip offer. Either PENDING, ACCEPTED, REJECTED or COMPLETED.
     */
    status: string;
}

