/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverEntity } from './driverEntity';
import { TripRequestEntity } from './tripRequestEntity';


export interface TripOfferEntity { 
    /**
     * The id of the entity.
     */
    id: number;
    /**
     * The creation time of the entity.
     */
    creationTime: number;
    /**
     * The modification time of the entity.
     */
    modificationTime: number;
    tripRequest?: TripRequestEntity;
    driver?: DriverEntity;
    status?: string;
}

