/**
 * SEP-Drive Gruppe P API
 *
 * Contact: mats.toncik@tnck.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents the data of an account that can be updated.
 */
export interface UpdateAccountDTO { 
    /**
     * Benutzername des Accounts
     */
    username?: string;
    /**
     * Vorname des Account-Inhabers
     */
    firstName?: string;
    /**
     * Nachname des Account-Inhabers
     */
    lastName?: string;
    /**
     * Geburtsdatum im Format YYYY-MM-DD
     */
    birthday?: string;
    /**
     * Typ des Autos nur bei drivers 
     */
    carType?: UpdateAccountDTO.CarTypeEnum;
}
export namespace UpdateAccountDTO {
    export const CarTypeEnum = {
        Small: 'SMALL',
        Medium: 'MEDIUM',
        Deluxe: 'DELUXE'
    } as const;
    export type CarTypeEnum = typeof CarTypeEnum[keyof typeof CarTypeEnum];
}


